name: Deploy to EC2 on master branch push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # updated private key
          HOST_DNS: ${{ secrets.HOST_DNS }}
        timeout-seconds: 30
        run: |
          echo "$SSH_PRIVATE_KEY" > keyfile
          chmod 600 keyfile
          mkdir -p ~/.ssh
          cp known_hosts ~/.ssh/known_hosts
          ssh -i keyfile ubuntu@$HOST_DNS "sudo bash ~/deploy.sh"
